version: '3.7'

services:
  instacode:
    build: .
    links:
      - snippetsdb:db
    depends_on:
      - snippetsdb
    environment:
      - MONGO_URI=mongodb://db/instacode
      # - PORT=8000
      - JWT_SECRET=secret
    ports:
      - '3000:8000'
    volumes:
      - ./src:/usr/src/app
      - nodemodules:/usr/src/app/node_modules
    command: npm run start
    networks:
      - instacode
  snippetsdb:
    image: mongo
    volumes:
      - mongodata:/data/db
    networks:
      - instacode
networks:
  instacode:
    name: instacode
    external: false
volumes:
  nodemodules:
    driver: local
  mongodata:
